module Brown where

import ProbSLG

-- 20 sentences from the Brown corpus, for training your POS tagger
brownDev :: Corpus TaggedWord
brownDev =
   [[TaggedWord ("College","nn"),TaggedWord ("teachers","nns"),TaggedWord ("in","in"),TaggedWord ("Texas","np"),TaggedWord ("are","ber"),TaggedWord ("not","*"),TaggedWord ("required","vbn"),TaggedWord ("to","to"),TaggedWord ("have","hv"),TaggedWord ("the","at"),TaggedWord ("Education","nn-tl"),TaggedWord ("courses","nns")]
   ,[TaggedWord ("Fifty-three","cd"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("150","cd"),TaggedWord ("representatives","nns"),TaggedWord ("immediately","rb"),TaggedWord ("joined","vbd"),TaggedWord ("Grover","np"),TaggedWord ("as","cs"),TaggedWord ("co-signers","nns"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("proposal","nn")]
   ,[TaggedWord ("Paris","np-hl"),TaggedWord (",",",-hl"),TaggedWord ("Texas","np-hl"),TaggedWord ("(","(-hl"),TaggedWord ("sp.","nn-hl"),TaggedWord (")",")-hl"),TaggedWord ("--","--"),TaggedWord ("The","at"),TaggedWord ("board","nn"),TaggedWord ("of","in"),TaggedWord ("regents","nns"),TaggedWord ("of","in"),TaggedWord ("Paris","np-tl"),TaggedWord ("Junior","jj-tl"),TaggedWord ("College","nn-tl"),TaggedWord ("has","hvz"),TaggedWord ("named","vbn"),TaggedWord ("Dr.","nn-tl"),TaggedWord ("Clarence","np"),TaggedWord ("Charles","np"),TaggedWord ("Clark","np"),TaggedWord ("of","in"),TaggedWord ("Hays","np"),TaggedWord (",",","),TaggedWord ("Kan.","np"),TaggedWord ("as","cs"),TaggedWord ("the","at"),TaggedWord ("school's","nn$"),TaggedWord ("new","jj"),TaggedWord ("president","nn")]
   ,[TaggedWord ("Dr.","nn-tl"),TaggedWord ("Clark","np"),TaggedWord ("will","md"),TaggedWord ("succeed","vb"),TaggedWord ("Dr.","nn-tl"),TaggedWord ("J.","np"),TaggedWord ("R.","np"),TaggedWord ("McLemore","np"),TaggedWord (",",","),TaggedWord ("who","wps"),TaggedWord ("will","md"),TaggedWord ("retire","vb"),TaggedWord ("at","in"),TaggedWord ("the","at"),TaggedWord ("close","nn"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("present","jj"),TaggedWord ("school","nn"),TaggedWord ("term","nn")]
   ,[TaggedWord ("Dr.","nn-tl"),TaggedWord ("Clark","np"),TaggedWord ("holds","vbz"),TaggedWord ("an","at"),TaggedWord ("earned","vbn"),TaggedWord ("Doctor","nn-tl"),TaggedWord ("of","in-tl"),TaggedWord ("Education","nn-tl"),TaggedWord ("degree","nn"),TaggedWord ("from","in"),TaggedWord ("the","at"),TaggedWord ("University","nn-tl"),TaggedWord ("of","in-tl"),TaggedWord ("Oklahoma","np-tl")]
   ,[TaggedWord ("He","pps"),TaggedWord ("also","rb"),TaggedWord ("received","vbd"),TaggedWord ("a","at"),TaggedWord ("Master","nn-tl"),TaggedWord ("of","in-tl"),TaggedWord ("Science","nn-tl"),TaggedWord ("degree","nn"),TaggedWord ("from","in"),TaggedWord ("Texas","np"),TaggedWord ("A","nn"),TaggedWord ("&","cc"),TaggedWord ("I","nn"),TaggedWord ("College","nn-tl"),TaggedWord ("and","cc"),TaggedWord ("a","at"),TaggedWord ("Bachelor","nn-tl"),TaggedWord ("of","in-tl"),TaggedWord ("Science","nn-tl"),TaggedWord ("degree","nn"),TaggedWord ("from","in"),TaggedWord ("Southwestern","jj-tl"),TaggedWord ("State","nn-tl"),TaggedWord ("College","nn-tl"),TaggedWord (",",","),TaggedWord ("Weatherford","np"),TaggedWord (",",","),TaggedWord ("Okla.","np")]
   ,[TaggedWord ("In","in"),TaggedWord ("addition","nn"),TaggedWord (",",","),TaggedWord ("Dr.","nn-tl"),TaggedWord ("Clark","np"),TaggedWord ("has","hvz"),TaggedWord ("studied","vbn"),TaggedWord ("at","in"),TaggedWord ("Rhode","np-tl"),TaggedWord ("Island","nn-tl"),TaggedWord ("State","nn-tl"),TaggedWord ("College","nn-tl"),TaggedWord ("and","cc"),TaggedWord ("Massachusetts","np-tl"),TaggedWord ("Institute","nn-tl"),TaggedWord ("of","in-tl"),TaggedWord ("Technology","nn-tl")]
   ,[TaggedWord ("During","in"),TaggedWord ("his","pp$"),TaggedWord ("college","nn"),TaggedWord ("career","nn"),TaggedWord (",",","),TaggedWord ("Dr.","nn-tl"),TaggedWord ("Clark","np"),TaggedWord ("was","bedz"),TaggedWord ("captain","nn"),TaggedWord ("of","in"),TaggedWord ("his","pp$"),TaggedWord ("basketball","nn"),TaggedWord ("team","nn"),TaggedWord ("and","cc"),TaggedWord ("was","bedz"),TaggedWord ("a","at"),TaggedWord ("football","nn"),TaggedWord ("letterman","nn")]
   ,[TaggedWord ("Dr.","nn-tl"),TaggedWord ("Clark","np"),TaggedWord ("has","hvz"),TaggedWord ("served","vbn"),TaggedWord ("as","cs"),TaggedWord ("teacher","nn"),TaggedWord ("and","cc"),TaggedWord ("principal","nn"),TaggedWord ("in","in"),TaggedWord ("Oklahoma","np"),TaggedWord ("high","jj"),TaggedWord ("schools","nns"),TaggedWord (",",","),TaggedWord ("as","cs"),TaggedWord ("teacher","nn"),TaggedWord ("and","cc"),TaggedWord ("athletic","jj"),TaggedWord ("director","nn"),TaggedWord ("at","in"),TaggedWord ("Raymondville","np"),TaggedWord (",",","),TaggedWord ("Texas","np"),TaggedWord (",",","),TaggedWord ("High","jj-tl"),TaggedWord ("School","nn-tl"),TaggedWord (",",","),TaggedWord ("as","cs"),TaggedWord ("an","at"),TaggedWord ("instructor","nn"),TaggedWord ("at","in"),TaggedWord ("the","at"),TaggedWord ("University","nn-tl"),TaggedWord ("of","in-tl"),TaggedWord ("Oklahoma","np-tl"),TaggedWord (",",","),TaggedWord ("and","cc"),TaggedWord ("as","cs"),TaggedWord ("an","at"),TaggedWord ("associate","jj"),TaggedWord ("professor","nn"),TaggedWord ("of","in"),TaggedWord ("education","nn"),TaggedWord ("at","in"),TaggedWord ("Fort","nn-tl"),TaggedWord ("Hays","np"),TaggedWord (",",","),TaggedWord ("Kan.","np"),TaggedWord (",",","),TaggedWord ("State","nn-tl"),TaggedWord ("College","nn-tl")]
   ,[TaggedWord ("He","pps"),TaggedWord ("has","hvz"),TaggedWord ("served","vbn"),TaggedWord ("as","cs"),TaggedWord ("a","at"),TaggedWord ("border","nn"),TaggedWord ("patrolman","nn"),TaggedWord ("and","cc"),TaggedWord ("was","bedz"),TaggedWord ("in","in"),TaggedWord ("the","at"),TaggedWord ("Signal","nn-tl"),TaggedWord ("Corps","nn-tl"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("U.S.","np-tl"),TaggedWord ("Army","nn-tl")]
   ,[TaggedWord ("Denton","np-hl"),TaggedWord (",",",-hl"),TaggedWord ("Texas","np-hl"),TaggedWord ("(","(-hl"),TaggedWord ("sp.","nn-hl"),TaggedWord (")",")-hl"),TaggedWord ("--","--"),TaggedWord ("Principals","nns"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("13","cd"),TaggedWord ("schools","nns"),TaggedWord ("in","in"),TaggedWord ("the","at"),TaggedWord ("Denton","np-tl"),TaggedWord ("Independent","jj-tl"),TaggedWord ("School","nn-tl"),TaggedWord ("District","nn-tl"),TaggedWord ("have","hv"),TaggedWord ("been","ben"),TaggedWord ("re-elected","vbn"),TaggedWord ("for","in"),TaggedWord ("the","at"),TaggedWord ("1961-62","cd"),TaggedWord ("session","nn"),TaggedWord ("upon","in"),TaggedWord ("the","at"),TaggedWord ("recommendation","nn"),TaggedWord ("of","in"),TaggedWord ("Supt.","nn-tl"),TaggedWord ("Chester","np"),TaggedWord ("O.","np"),TaggedWord ("Strickland","np")]
   ,[TaggedWord ("State","nn"),TaggedWord ("and","cc"),TaggedWord ("federal","jj"),TaggedWord ("legislation","nn"),TaggedWord ("against","in"),TaggedWord ("racial","jj"),TaggedWord ("discrimination","nn"),TaggedWord ("in","in"),TaggedWord ("employment","nn"),TaggedWord ("was","bedz"),TaggedWord ("called","vbn"),TaggedWord ("for","in"),TaggedWord ("yesterday","nr"),TaggedWord ("in","in"),TaggedWord ("a","at"),TaggedWord ("report","nn"),TaggedWord ("of","in"),TaggedWord ("a","at"),TaggedWord ("``","``"),TaggedWord ("blue","jj"),TaggedWord ("ribbon","nn"),TaggedWord ("''","''"),TaggedWord ("citizens","nns"),TaggedWord ("committee","nn"),TaggedWord ("on","in"),TaggedWord ("the","at"),TaggedWord ("aid","nn"),TaggedWord ("to","in"),TaggedWord ("dependent","jj"),TaggedWord ("children","nns"),TaggedWord ("program","vb")]
   ,[TaggedWord ("The","at"),TaggedWord ("report","nn"),TaggedWord (",",","),TaggedWord ("culminating","vbg"),TaggedWord ("a","at"),TaggedWord ("year","nn"),TaggedWord ("long","jj"),TaggedWord ("study","nn"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("ADC","nn"),TaggedWord ("program","nn"),TaggedWord ("in","in"),TaggedWord ("Cook","np"),TaggedWord ("county","nn"),TaggedWord ("by","in"),TaggedWord ("a","at"),TaggedWord ("New","jj-tl"),TaggedWord ("York","np-tl"),TaggedWord ("City","nn-tl"),TaggedWord ("welfare","nn"),TaggedWord ("consulting","vbg"),TaggedWord ("firm","nn"),TaggedWord (",",","),TaggedWord ("listed","vbd"),TaggedWord ("10","cd"),TaggedWord ("long","jj"),TaggedWord ("range","nn"),TaggedWord ("recommendations","nns"),TaggedWord ("designed","vbn"),TaggedWord ("to","to"),TaggedWord ("reduce","vb"),TaggedWord ("the","at"),TaggedWord ("soaring","vbg"),TaggedWord ("ADC","nn"),TaggedWord ("case","nn"),TaggedWord ("load","nn")]
   ,[TaggedWord ("The","at"),TaggedWord ("report","nn"),TaggedWord ("called","vbd"),TaggedWord ("racial","jj"),TaggedWord ("discrimination","nn"),TaggedWord ("in","in"),TaggedWord ("employment","nn"),TaggedWord ("``","``"),TaggedWord ("one","cd"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("most","ql"),TaggedWord ("serious","jj"),TaggedWord ("causes","nns"),TaggedWord ("of","in"),TaggedWord ("family","nn"),TaggedWord ("breakdown","nn"),TaggedWord (",",","),TaggedWord ("desertion","nn"),TaggedWord (",",","),TaggedWord ("and","cc"),TaggedWord ("ADC","nn"),TaggedWord ("dependency","nn"),TaggedWord ("''","''")]
   ,[TaggedWord ("``","``"),TaggedWord ("Must","md-hl"),TaggedWord ("solve","vb-hl"),TaggedWord ("problem","nn-hl"),TaggedWord ("''","''"),TaggedWord ("The","at"),TaggedWord ("monthly","jj"),TaggedWord ("cost","nn"),TaggedWord ("of","in"),TaggedWord ("ADC","nn"),TaggedWord ("to","in"),TaggedWord ("more","ap"),TaggedWord ("than","in"),TaggedWord ("100,000","cd"),TaggedWord ("recipients","nns"),TaggedWord ("in","in"),TaggedWord ("the","at"),TaggedWord ("county","nn"),TaggedWord ("is","bez"),TaggedWord ("4.4","cd"),TaggedWord ("million","cd"),TaggedWord ("dollars","nns"),TaggedWord (",",","),TaggedWord ("said","vbd"),TaggedWord ("C.","np"),TaggedWord ("Virgil","np"),TaggedWord ("Martin","np"),TaggedWord (",",","),TaggedWord ("president","nn"),TaggedWord ("of","in"),TaggedWord ("Carson","np"),TaggedWord ("Pirie","np"),TaggedWord ("Scott","np"),TaggedWord ("&","cc-tl"),TaggedWord ("Co.","nn-tl"),TaggedWord (",",","),TaggedWord ("committee","nn"),TaggedWord ("chairman","nn")]
   ,[TaggedWord ("``","``"),TaggedWord ("We","ppss"),TaggedWord ("must","md"),TaggedWord ("solve","vb"),TaggedWord ("the","at"),TaggedWord ("problems","nns"),TaggedWord ("which","wdt"),TaggedWord ("have","hv"),TaggedWord ("forced","vbn"),TaggedWord ("these","dts"),TaggedWord ("people","nns"),TaggedWord ("to","to"),TaggedWord ("depend","vb"),TaggedWord ("upon","in"),TaggedWord ("ADC","nn"),TaggedWord ("for","in"),TaggedWord ("subsistence","nn"),TaggedWord ("''","''"),TaggedWord (",",","),TaggedWord ("Martin","np"),TaggedWord ("said","vbd")]
   ,[TaggedWord ("The","at"),TaggedWord ("volume","nn"),TaggedWord ("of","in"),TaggedWord ("ADC","nn"),TaggedWord ("cases","nns"),TaggedWord ("will","md"),TaggedWord ("decrease","vb"),TaggedWord (",",","),TaggedWord ("Martin","np"),TaggedWord ("reported","vbd"),TaggedWord (",",","),TaggedWord ("when","wrb"),TaggedWord ("the","at"),TaggedWord ("community","nn"),TaggedWord ("is","bez"),TaggedWord ("able","jj"),TaggedWord ("to","to"),TaggedWord ("deal","vb"),TaggedWord ("effectively","rb"),TaggedWord ("with","in"),TaggedWord ("two","cd"),TaggedWord ("problems","nns"),TaggedWord (":",":"),TaggedWord ("Relatively","rb"),TaggedWord ("limited","vbn"),TaggedWord ("skills","nns"),TaggedWord ("and","cc"),TaggedWord ("discrimination","nn"),TaggedWord ("in","in"),TaggedWord ("employment","nn"),TaggedWord ("because","rb"),TaggedWord ("of","in"),TaggedWord ("color","nn")]
   ,[TaggedWord ("These","dts"),TaggedWord (",",","),TaggedWord ("he","pps"),TaggedWord ("said","vbd"),TaggedWord (",",","),TaggedWord ("are","ber"),TaggedWord ("``","``"),TaggedWord ("two","cd"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("principal","jjs"),TaggedWord ("underlying","vbg"),TaggedWord ("causes","nns"),TaggedWord ("for","in"),TaggedWord ("family","nn"),TaggedWord ("breakups","nns"),TaggedWord ("leading","vbg"),TaggedWord ("to","in"),TaggedWord ("ADC","nn"),TaggedWord ("''","''")]
   ,[TaggedWord ("Calls","vbz-hl"),TaggedWord ("for","in-hl"),TaggedWord ("extension","nn-hl"),TaggedWord ("Other","ap"),TaggedWord ("recommendations","nns"),TaggedWord ("made","vbn"),TaggedWord ("by","in"),TaggedWord ("the","at"),TaggedWord ("committee","nn"),TaggedWord ("are","ber"),TaggedWord (":",":"),TaggedWord ("Extension","nn"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("ADC","nn"),TaggedWord ("program","nn"),TaggedWord ("to","in"),TaggedWord ("all","abn"),TaggedWord ("children","nns"),TaggedWord ("in","in"),TaggedWord ("need","nn"),TaggedWord ("living","vbg"),TaggedWord ("with","in"),TaggedWord ("any","dti"),TaggedWord ("relatives","nns"),TaggedWord (",",","),TaggedWord ("including","in"),TaggedWord ("both","abx"),TaggedWord ("parents","nns"),TaggedWord (",",","),TaggedWord ("as","cs"),TaggedWord ("a","at"),TaggedWord ("means","nns"),TaggedWord ("of","in"),TaggedWord ("preserving","vbg"),TaggedWord ("family","nn"),TaggedWord ("unity","nn")]
   ,[TaggedWord ("Research","nn"),TaggedWord ("projects","nns"),TaggedWord ("as","ql"),TaggedWord ("soon","rb"),TaggedWord ("as","cs"),TaggedWord ("possible","jj"),TaggedWord ("on","in"),TaggedWord ("the","at"),TaggedWord ("causes","nns"),TaggedWord ("and","cc"),TaggedWord ("prevention","nn"),TaggedWord ("of","in"),TaggedWord ("dependency","nn"),TaggedWord ("and","cc"),TaggedWord ("illegitimacy","nn")]
   ]


-- Another 20 sentences from the Brown corpus, 
-- for testing your POS tagger after it has been trained on the "brownDev" sentences

brownShort :: Corpus TaggedWord
brownShort =
   [[TaggedWord ("The","D"),TaggedWord ("jury","N"),TaggedWord ("further","Adv"),TaggedWord ("said","V")],
    [TaggedWord ("The","D"),TaggedWord ("September-October","N"),TaggedWord ("term","N"),TaggedWord ("jury","N")]
   ]

-- [TaggedWord ("The","D"),TaggedWord ("jury","N"),TaggedWord ("further","Adv"),TaggedWord ("said","V")]
brownTest :: Corpus TaggedWord
brownTest =
   [[TaggedWord ("The","at"),TaggedWord ("Fulton","np-tl"),TaggedWord ("County","nn-tl"),TaggedWord ("Grand","jj-tl"),TaggedWord ("Jury","nn-tl"),TaggedWord ("said","vbd"),TaggedWord ("Friday","nr"),TaggedWord ("an","at"),TaggedWord ("investigation","nn"),TaggedWord ("of","in"),TaggedWord ("Atlanta's","np$"),TaggedWord ("recent","jj"),TaggedWord ("primary","nn"),TaggedWord ("election","nn"),TaggedWord ("produced","vbd"),TaggedWord ("``","``"),TaggedWord ("no","at"),TaggedWord ("evidence","nn"),TaggedWord ("''","''"),TaggedWord ("that","cs"),TaggedWord ("any","dti"),TaggedWord ("irregularities","nns"),TaggedWord ("took","vbd"),TaggedWord ("place","nn")]
   ,[TaggedWord ("The","at"),TaggedWord ("jury","nn"),TaggedWord ("further","rbr"),TaggedWord ("said","vbd"),TaggedWord ("in","in"),TaggedWord ("term-end","nn"),TaggedWord ("presentments","nns"),TaggedWord ("that","cs"),TaggedWord ("the","at"),TaggedWord ("City","nn-tl"),TaggedWord ("Executive","jj-tl"),TaggedWord ("Committee","nn-tl"),TaggedWord (",",","),TaggedWord ("which","wdt"),TaggedWord ("had","hvd"),TaggedWord ("over-all","jj"),TaggedWord ("charge","nn"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("election","nn"),TaggedWord (",",","),TaggedWord ("``","``"),TaggedWord ("deserves","vbz"),TaggedWord ("the","at"),TaggedWord ("praise","nn"),TaggedWord ("and","cc"),TaggedWord ("thanks","nns"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("City","nn-tl"),TaggedWord ("of","in-tl"),TaggedWord ("Atlanta","np-tl"),TaggedWord ("''","''"),TaggedWord ("for","in"),TaggedWord ("the","at"),TaggedWord ("manner","nn"),TaggedWord ("in","in"),TaggedWord ("which","wdt"),TaggedWord ("the","at"),TaggedWord ("election","nn"),TaggedWord ("was","bedz"),TaggedWord ("conducted","vbn")]
   ,[TaggedWord ("The","at"),TaggedWord ("September-October","np"),TaggedWord ("term","nn"),TaggedWord ("jury","nn"),TaggedWord ("had","hvd"),TaggedWord ("been","ben"),TaggedWord ("charged","vbn"),TaggedWord ("by","in"),TaggedWord ("Fulton","np-tl"),TaggedWord ("Superior","jj-tl"),TaggedWord ("Court","nn-tl"),TaggedWord ("Judge","nn-tl"),TaggedWord ("Durwood","np"),TaggedWord ("Pye","np"),TaggedWord ("to","to"),TaggedWord ("investigate","vb"),TaggedWord ("reports","nns"),TaggedWord ("of","in"),TaggedWord ("possible","jj"),TaggedWord ("``","``"),TaggedWord ("irregularities","nns"),TaggedWord ("''","''"),TaggedWord ("in","in"),TaggedWord ("the","at"),TaggedWord ("hard-fought","jj"),TaggedWord ("primary","nn"),TaggedWord ("which","wdt"),TaggedWord ("was","bedz"),TaggedWord ("won","vbn"),TaggedWord ("by","in"),TaggedWord ("Mayor-nominate","nn-tl"),TaggedWord ("Ivan","np"),TaggedWord ("Allen","np"),TaggedWord ("Jr.","np")]
   ,[TaggedWord ("``","``"),TaggedWord ("Only","rb"),TaggedWord ("a","at"),TaggedWord ("relative","jj"),TaggedWord ("handful","nn"),TaggedWord ("of","in"),TaggedWord ("such","jj"),TaggedWord ("reports","nns"),TaggedWord ("was","bedz"),TaggedWord ("received","vbn"),TaggedWord ("''","''"),TaggedWord (",",","),TaggedWord ("the","at"),TaggedWord ("jury","nn"),TaggedWord ("said","vbd"),TaggedWord (",",","),TaggedWord ("``","``"),TaggedWord ("considering","in"),TaggedWord ("the","at"),TaggedWord ("widespread","jj"),TaggedWord ("interest","nn"),TaggedWord ("in","in"),TaggedWord ("the","at"),TaggedWord ("election","nn"),TaggedWord (",",","),TaggedWord ("the","at"),TaggedWord ("number","nn"),TaggedWord ("of","in"),TaggedWord ("voters","nns"),TaggedWord ("and","cc"),TaggedWord ("the","at"),TaggedWord ("size","nn"),TaggedWord ("of","in"),TaggedWord ("this","dt"),TaggedWord ("city","nn"),TaggedWord ("''","''")]
   ,[TaggedWord ("The","at"),TaggedWord ("jury","nn"),TaggedWord ("said","vbd"),TaggedWord ("it","pps"),TaggedWord ("did","dod"),TaggedWord ("find","vb"),TaggedWord ("that","cs"),TaggedWord ("many","ap"),TaggedWord ("of","in"),TaggedWord ("Georgia's","np$"),TaggedWord ("registration","nn"),TaggedWord ("and","cc"),TaggedWord ("election","nn"),TaggedWord ("laws","nns"),TaggedWord ("``","``"),TaggedWord ("are","ber"),TaggedWord ("outmoded","jj"),TaggedWord ("or","cc"),TaggedWord ("inadequate","jj"),TaggedWord ("and","cc"),TaggedWord ("often","rb"),TaggedWord ("ambiguous","jj"),TaggedWord ("''","''")]
   ,[TaggedWord ("It","pps"),TaggedWord ("recommended","vbd"),TaggedWord ("that","cs"),TaggedWord ("Fulton","np"),TaggedWord ("legislators","nns"),TaggedWord ("act","vb"),TaggedWord ("``","``"),TaggedWord ("to","to"),TaggedWord ("have","hv"),TaggedWord ("these","dts"),TaggedWord ("laws","nns"),TaggedWord ("studied","vbn"),TaggedWord ("and","cc"),TaggedWord ("revised","vbn"),TaggedWord ("to","in"),TaggedWord ("the","at"),TaggedWord ("end","nn"),TaggedWord ("of","in"),TaggedWord ("modernizing","vbg"),TaggedWord ("and","cc"),TaggedWord ("improving","vbg"),TaggedWord ("them","ppo"),TaggedWord ("''","''")]
   ,[TaggedWord ("The","at"),TaggedWord ("grand","jj"),TaggedWord ("jury","nn"),TaggedWord ("commented","vbd"),TaggedWord ("on","in"),TaggedWord ("a","at"),TaggedWord ("number","nn"),TaggedWord ("of","in"),TaggedWord ("other","ap"),TaggedWord ("topics","nns"),TaggedWord (",",","),TaggedWord ("among","in"),TaggedWord ("them","ppo"),TaggedWord ("the","at"),TaggedWord ("Atlanta","np"),TaggedWord ("and","cc"),TaggedWord ("Fulton","np-tl"),TaggedWord ("County","nn-tl"),TaggedWord ("purchasing","vbg"),TaggedWord ("departments","nns"),TaggedWord ("which","wdt"),TaggedWord ("it","pps"),TaggedWord ("said","vbd"),TaggedWord ("``","``"),TaggedWord ("are","ber"),TaggedWord ("well","ql"),TaggedWord ("operated","vbn"),TaggedWord ("and","cc"),TaggedWord ("follow","vb"),TaggedWord ("generally","rb"),TaggedWord ("accepted","vbn"),TaggedWord ("practices","nns"),TaggedWord ("which","wdt"),TaggedWord ("inure","vb"),TaggedWord ("to","in"),TaggedWord ("the","at"),TaggedWord ("best","jjt"),TaggedWord ("interest","nn"),TaggedWord ("of","in"),TaggedWord ("both","abx"),TaggedWord ("governments","nns"),TaggedWord ("''","''")]
   ,[TaggedWord ("Merger","nn-hl"),TaggedWord ("proposed","vbn-hl"),TaggedWord ("However","wrb"),TaggedWord (",",","),TaggedWord ("the","at"),TaggedWord ("jury","nn"),TaggedWord ("said","vbd"),TaggedWord ("it","pps"),TaggedWord ("believes","vbz"),TaggedWord ("``","``"),TaggedWord ("these","dts"),TaggedWord ("two","cd"),TaggedWord ("offices","nns"),TaggedWord ("should","md"),TaggedWord ("be","be"),TaggedWord ("combined","vbn"),TaggedWord ("to","to"),TaggedWord ("achieve","vb"),TaggedWord ("greater","jjr"),TaggedWord ("efficiency","nn"),TaggedWord ("and","cc"),TaggedWord ("reduce","vb"),TaggedWord ("the","at"),TaggedWord ("cost","nn"),TaggedWord ("of","in"),TaggedWord ("administration","nn"),TaggedWord ("''","''")]
   ,[TaggedWord ("The","at"),TaggedWord ("City","nn-tl"),TaggedWord ("Purchasing","vbg-tl"),TaggedWord ("Department","nn-tl"),TaggedWord (",",","),TaggedWord ("the","at"),TaggedWord ("jury","nn"),TaggedWord ("said","vbd"),TaggedWord (",",","),TaggedWord ("``","``"),TaggedWord ("is","bez"),TaggedWord ("lacking","vbg"),TaggedWord ("in","in"),TaggedWord ("experienced","vbn"),TaggedWord ("clerical","jj"),TaggedWord ("personnel","nns"),TaggedWord ("as","cs"),TaggedWord ("a","at"),TaggedWord ("result","nn"),TaggedWord ("of","in"),TaggedWord ("city","nn"),TaggedWord ("personnel","nns"),TaggedWord ("policies","nns"),TaggedWord ("''","''")]
   ,[TaggedWord ("It","pps"),TaggedWord ("urged","vbd"),TaggedWord ("that","cs"),TaggedWord ("the","at"),TaggedWord ("city","nn"),TaggedWord ("``","``"),TaggedWord ("take","vb"),TaggedWord ("steps","nns"),TaggedWord ("to","to"),TaggedWord ("remedy","vb"),TaggedWord ("''","''"),TaggedWord ("this","dt"),TaggedWord ("problem","nn")]
   ,[TaggedWord ("Implementation","nn"),TaggedWord ("of","in"),TaggedWord ("Georgia's","np$"),TaggedWord ("automobile","nn"),TaggedWord ("title","nn"),TaggedWord ("law","nn"),TaggedWord ("was","bedz"),TaggedWord ("also","rb"),TaggedWord ("recommended","vbn"),TaggedWord ("by","in"),TaggedWord ("the","at"),TaggedWord ("outgoing","jj"),TaggedWord ("jury","nn")]
   ,[TaggedWord ("It","pps"),TaggedWord ("urged","vbd"),TaggedWord ("that","cs"),TaggedWord ("the","at"),TaggedWord ("next","ap"),TaggedWord ("Legislature","nn-tl"),TaggedWord ("``","``"),TaggedWord ("provide","vb"),TaggedWord ("enabling","vbg"),TaggedWord ("funds","nns"),TaggedWord ("and","cc"),TaggedWord ("re-set","vb"),TaggedWord ("the","at"),TaggedWord ("effective","jj"),TaggedWord ("date","nn"),TaggedWord ("so","cs"),TaggedWord ("that","cs"),TaggedWord ("an","at"),TaggedWord ("orderly","jj"),TaggedWord ("implementation","nn"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("law","nn"),TaggedWord ("may","md"),TaggedWord ("be","be"),TaggedWord ("effected","vbn"),TaggedWord ("''","''")]
   ,[TaggedWord ("The","at"),TaggedWord ("grand","jj"),TaggedWord ("jury","nn"),TaggedWord ("took","vbd"),TaggedWord ("a","at"),TaggedWord ("swipe","nn"),TaggedWord ("at","in"),TaggedWord ("the","at"),TaggedWord ("State","nn-tl"),TaggedWord ("Welfare","nn-tl"),TaggedWord ("Department's","nn$-tl"),TaggedWord ("handling","nn"),TaggedWord ("of","in"),TaggedWord ("federal","jj"),TaggedWord ("funds","nns"),TaggedWord ("granted","vbn"),TaggedWord ("for","in"),TaggedWord ("child","nn"),TaggedWord ("welfare","nn"),TaggedWord ("services","nns"),TaggedWord ("in","in"),TaggedWord ("foster","jj"),TaggedWord ("homes","nns")]
   ,[TaggedWord ("``","``"),TaggedWord ("This","dt"),TaggedWord ("is","bez"),TaggedWord ("one","cd"),TaggedWord ("of","in"),TaggedWord ("the","at"),TaggedWord ("major","jj"),TaggedWord ("items","nns"),TaggedWord ("in","in"),TaggedWord ("the","at"),TaggedWord ("Fulton","np-tl"),TaggedWord ("County","nn-tl"),TaggedWord ("general","jj"),TaggedWord ("assistance","nn"),TaggedWord ("program","nn"),TaggedWord ("''","''"),TaggedWord (",",","),TaggedWord ("the","at"),TaggedWord ("jury","nn"),TaggedWord ("said","vbd"),TaggedWord (",",","),TaggedWord ("but","cc"),TaggedWord ("the","at"),TaggedWord ("State","nn-tl"),TaggedWord ("Welfare","nn-tl"),TaggedWord ("Department","nn-tl"),TaggedWord ("``","``"),TaggedWord ("has","hvz"),TaggedWord ("seen","vbn"),TaggedWord ("fit","jj"),TaggedWord ("to","to"),TaggedWord ("distribute","vb"),TaggedWord ("these","dts"),TaggedWord ("funds","nns"),TaggedWord ("through","in"),TaggedWord ("the","at"),TaggedWord ("welfare","nn"),TaggedWord ("departments","nns"),TaggedWord ("of","in"),TaggedWord ("all","abn"),TaggedWord ("the","at"),TaggedWord ("counties","nns"),TaggedWord ("in","in"),TaggedWord ("the","at"),TaggedWord ("state","nn"),TaggedWord ("with","in"),TaggedWord ("the","at"),TaggedWord ("exception","nn"),TaggedWord ("of","in"),TaggedWord ("Fulton","np-tl"),TaggedWord ("County","nn-tl"),TaggedWord (",",","),TaggedWord ("which","wdt"),TaggedWord ("receives","vbz"),TaggedWord ("none","pn"),TaggedWord ("of","in"),TaggedWord ("this","dt"),TaggedWord ("money","nn")]
   ,[TaggedWord ("The","at"),TaggedWord ("jurors","nns"),TaggedWord ("said","vbd"),TaggedWord ("they","ppss"),TaggedWord ("realize","vb"),TaggedWord ("``","``"),TaggedWord ("a","at"),TaggedWord ("proportionate","jj"),TaggedWord ("distribution","nn"),TaggedWord ("of","in"),TaggedWord ("these","dts"),TaggedWord ("funds","nns"),TaggedWord ("might","md"),TaggedWord ("disable","vb"),TaggedWord ("this","dt"),TaggedWord ("program","nn"),TaggedWord ("in","in"),TaggedWord ("our","pp$"),TaggedWord ("less","ql"),TaggedWord ("populous","jj"),TaggedWord ("counties","nns"),TaggedWord ("''","''")]
   ,[TaggedWord ("Nevertheless","rb"),TaggedWord (",",","),TaggedWord ("``","``"),TaggedWord ("we","ppss"),TaggedWord ("feel","vb"),TaggedWord ("that","cs"),TaggedWord ("in","in"),TaggedWord ("the","at"),TaggedWord ("future","nn"),TaggedWord ("Fulton","np-tl"),TaggedWord ("County","nn-tl"),TaggedWord ("should","md"),TaggedWord ("receive","vb"),TaggedWord ("some","dti"),TaggedWord ("portion","nn"),TaggedWord ("of","in"),TaggedWord ("these","dts"),TaggedWord ("available","jj"),TaggedWord ("funds","nns"),TaggedWord ("''","''"),TaggedWord (",",","),TaggedWord ("the","at"),TaggedWord ("jurors","nns"),TaggedWord ("said","vbd")]
   ,[TaggedWord ("``","``"),TaggedWord ("Failure","nn"),TaggedWord ("to","to"),TaggedWord ("do","do"),TaggedWord ("this","dt"),TaggedWord ("will","md"),TaggedWord ("continue","vb"),TaggedWord ("to","to"),TaggedWord ("place","vb"),TaggedWord ("a","at"),TaggedWord ("disproportionate","jj"),TaggedWord ("burden","nn"),TaggedWord ("''","''"),TaggedWord ("on","in"),TaggedWord ("Fulton","np"),TaggedWord ("taxpayers","nns")]
   ,[TaggedWord ("The","at"),TaggedWord ("jury","nn"),TaggedWord ("also","rb"),TaggedWord ("commented","vbd"),TaggedWord ("on","in"),TaggedWord ("the","at"),TaggedWord ("Fulton","np"),TaggedWord ("ordinary's","nn$"),TaggedWord ("court","nn"),TaggedWord ("which","wdt"),TaggedWord ("has","hvz"),TaggedWord ("been","ben"),TaggedWord ("under","in"),TaggedWord ("fire","nn"),TaggedWord ("for","in"),TaggedWord ("its","pp$"),TaggedWord ("practices","nns"),TaggedWord ("in","in"),TaggedWord ("the","at"),TaggedWord ("appointment","nn"),TaggedWord ("of","in"),TaggedWord ("appraisers","nns"),TaggedWord (",",","),TaggedWord ("guardians","nns"),TaggedWord ("and","cc"),TaggedWord ("administrators","nns"),TaggedWord ("and","cc"),TaggedWord ("the","at"),TaggedWord ("awarding","nn"),TaggedWord ("of","in"),TaggedWord ("fees","nns"),TaggedWord ("and","cc"),TaggedWord ("compensation","nn")]
   ,[TaggedWord ("Wards","nns-hl"),TaggedWord ("protected","vbn-hl"),TaggedWord ("The","at"),TaggedWord ("jury","nn"),TaggedWord ("said","vbd"),TaggedWord ("it","pps"),TaggedWord ("found","vbd"),TaggedWord ("the","at"),TaggedWord ("court","nn"),TaggedWord ("``","``"),TaggedWord ("has","hvz"),TaggedWord ("incorporated","vbn"),TaggedWord ("into","in"),TaggedWord ("its","pp$"),TaggedWord ("operating","vbg"),TaggedWord ("procedures","nns"),TaggedWord ("the","at"),TaggedWord ("recommendations","nns"),TaggedWord ("''","''"),TaggedWord ("of","in"),TaggedWord ("two","cd"),TaggedWord ("previous","jj"),TaggedWord ("grand","jj"),TaggedWord ("juries","nns"),TaggedWord (",",","),TaggedWord ("the","at"),TaggedWord ("Atlanta","np-tl"),TaggedWord ("Bar","nn-tl"),TaggedWord ("Association","nn-tl"),TaggedWord ("and","cc"),TaggedWord ("an","at"),TaggedWord ("interim","nn"),TaggedWord ("citizens","nns"),TaggedWord ("committee","nn")]
   ,[TaggedWord ("``","``"),TaggedWord ("These","dts"),TaggedWord ("actions","nns"),TaggedWord ("should","md"),TaggedWord ("serve","vb"),TaggedWord ("to","to"),TaggedWord ("protect","vb"),TaggedWord ("in","in"),TaggedWord ("fact","nn"),TaggedWord ("and","cc"),TaggedWord ("in","in"),TaggedWord ("effect","nn"),TaggedWord ("the","at"),TaggedWord ("court's","nn$"),TaggedWord ("wards","nns"),TaggedWord ("from","in"),TaggedWord ("undue","jj"),TaggedWord ("costs","nns"),TaggedWord ("and","cc"),TaggedWord ("its","pp$"),TaggedWord ("appointed","vbn"),TaggedWord ("and","cc"),TaggedWord ("elected","vbn"),TaggedWord ("servants","nns"),TaggedWord ("from","in"),TaggedWord ("unmeritorious","jj"),TaggedWord ("criticisms","nns"),TaggedWord ("''","''"),TaggedWord (",",","),TaggedWord ("the","at"),TaggedWord ("jury","nn"),TaggedWord ("said","vbd")]
   ]
